import { test, expect } from '@playwright/test';
test('real Avalonia WASM workbench: boot, source edits, history, insertion, errors, navigation', async ({ page }, testInfo) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') console.log('browser:', message.text()); });
  await page.goto('/');
  await page.waitForFunction(() => window.prodesigner?.state().ready, null, { timeout: 150000 });
  await expect(page.locator('#boot')).toHaveCount(0, { timeout: 15000 });
  await page.waitForTimeout(1200);
  const state = () => page.evaluate(() => window.prodesigner.state());
  const initial = await state();
  expect(initial.document).toBe('Dashboard.axaml'); expect(initial.nodes).toBeGreaterThan(60);
  await page.evaluate(() => { window.prodesigner.select('RevenueCard'); window.prodesigner.setProperty('Width', '264'); });
  expect((await state()).source).toContain('Width="264"');
  await page.evaluate(() => window.prodesigner.command('undo'));
  expect((await state()).source).toBe(initial.source);
  await page.evaluate(() => window.prodesigner.command('redo'));
  expect((await state()).source).toContain('Width="264"');
  await page.evaluate(() => { window.prodesigner.select('DashboardCanvas'); window.prodesigner.insert('Button'); });
  expect((await state()).source).toContain('x:Name="Button1"');
  await page.waitForTimeout(500);
  await page.screenshot({ path: testInfo.outputPath('prodesigner-desktop.png'), fullPage: true });
  const valid = await state();
  await page.evaluate(() => window.prodesigner.setSource('<UserControl>'));
  expect((await state()).valid).toBe(false); expect((await state()).nodes).toBe(valid.nodes);
  await page.evaluate(() => window.prodesigner.command('undo'));
  expect((await state()).valid).toBe(true);
  await page.evaluate(() => window.prodesigner.command('new'));
  expect((await state()).documents).toBe(4);
  await page.evaluate(() => window.prodesigner.insert('Rectangle'));
  expect((await state()).source).toContain('Rectangle');
  await page.keyboard.press('Control+k'); await page.waitForTimeout(150);
  await page.screenshot({ path: testInfo.outputPath('prodesigner-command-palette.png') });
  await page.keyboard.press('Escape');
  expect(errors).toEqual([]);
});
