<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../ProDesigner.Authoring/ProDesigner.Authoring.csproj" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.4" />
  </ItemGroup>
</Project>
