<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><IsPackable>false</IsPackable><ApplicationManifest>app.manifest</ApplicationManifest></PropertyGroup><ItemGroup><ProjectReference Include="../../src/ProDesigner.Runtime/ProDesigner.Runtime.csproj" /><ProjectReference Include="../../src/ProDesigner.Workbench/ProDesigner.Workbench.csproj" /><ProjectReference Include="../../src/ProDesigner.Roslyn/ProDesigner.Roslyn.csproj" /><ProjectReference Include="../../src/ProDesigner.Workspaces/ProDesigner.Workspaces.csproj" /><PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" /><PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="$(AvaloniaVersion)" /></ItemGroup></Project>
