<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../ProDesigner.Core/ProDesigner.Core.csproj" /><PackageReference Include="Microsoft.Build.Locator" Version="1.7.8" /><PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="$(RoslynVersion)" /><PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="$(RoslynVersion)" /></ItemGroup></Project>
