<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../ProDesigner.Animation/ProDesigner.Animation.csproj" /><ProjectReference Include="../ProDesigner.Core/ProDesigner.Core.csproj" /><ProjectReference Include="../ProDesigner.DesignSystems/ProDesigner.DesignSystems.csproj" /><ProjectReference Include="../ProDesigner.Prototyping/ProDesigner.Prototyping.csproj" /></ItemGroup></Project>
